### ISSUE TITLE
pre and post actions for a travis.yml

### ISSUE THREAD

**Issue by imlucas** [mongodb-js/runner#2]
Travis docs have this sleep 15 solution http://docs.travis-ci.com/user/database-setup/#MongoDB

We already have to solve this problem for lots of our own stuff.  Use @imlucas/squirrel-server + mongodb-runner to provide a one-liner for a before_script

```yaml
before_script:
  - curl -fsSL http://mongodb.land/runner/install | bash && mongodb-runner
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
after_script:
   - mongodb-runner stop
```

Could also be a good spot to get people to use @imlucas/mongodb-datasets for test fixtures.
